// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package perf_monitor_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [30:0] q;
    } data;
    struct packed {
      logic        q;
    } v;
  } perf_monitor_reg2hw_perf_data_reg_t;

  typedef struct packed {
    struct packed {
      logic [30:0] d;
      logic        de;
    } data;
    struct packed {
      logic        d;
      logic        de;
    } v;
  } perf_monitor_hw2reg_perf_data_reg_t;

  // Register -> HW type
  typedef struct packed {
    perf_monitor_reg2hw_perf_data_reg_t perf_data; // [31:0]
  } perf_monitor_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    perf_monitor_hw2reg_perf_data_reg_t perf_data; // [33:0]
  } perf_monitor_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PERF_MONITOR_PERF_DATA_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    PERF_MONITOR_PERF_DATA
  } perf_monitor_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PERF_MONITOR_PERMIT [1] = '{
    4'b 1111  // index[0] PERF_MONITOR_PERF_DATA
  };

endpackage

